/**
 * probe_delta_reload.m — Does ANE delta reload actually update weight values?
 *
 * Claim from external ane.h:
 *   "ANE bakes weights into HWX at compile time and does not re-read them
 *    on reload. Use ane_mil_linear_dynamic() instead for training."
 *
 * Test protocol:
 *   1. Compile an identity conv1x1 [1,16,1,8] with diagonal weight = 1.0.
 *      Input: all 1.0 fp16.  Expected output: all 1.0 fp16.
 *   2. Execute and record output_phase1[].
 *   3. Delta reload: unload → overwrite weight file with 2× diagonal (2.0 on
 *      diagonal) → loadWithQoS: (no recompile).
 *   4. Execute again and record output_phase2[].
 *
 *   Verdict:
 *     output_phase2 ≠ output_phase1  → weights DID update (delta reload works)
 *     output_phase2 == output_phase1 → weights did NOT update (baked at compile)
 *
 * Model: identity conv1x1 [1,16,1,8] (from probe_perf_stats — known to compile).
 * Weight: [OC=16, IC=1, kH=1, kW=16] — 256 fp16 values.
 *   identity: w[i*16 + i] = 1.0 for i in 0..15
 *   2x:       w[i*16 + i] = 2.0 for i in 0..15
 *
 * Build:
 *   clang -x objective-c++ -std=c++17 -fobjc-arc -framework Foundation \
 *         -framework IOSurface -lc++ \
 *         -o probe_delta_reload probe_delta_reload.m && ./probe_delta_reload
 */

#import <Foundation/Foundation.h>
#import <IOSurface/IOSurface.h>
#import <objc/runtime.h>
#import <objc/message.h>
#include <dlfcn.h>
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <math.h>

static constexpr const char* kFrameworkPath =
    "/System/Library/PrivateFrameworks/AppleNeuralEngine.framework/AppleNeuralEngine";
static constexpr unsigned int kQoS = 21;

static constexpr uint16_t kFP16_0  = 0x0000;  // 0.0
static constexpr uint16_t kFP16_1  = 0x3C00;  // 1.0
static constexpr uint16_t kFP16_2  = 0x4000;  // 2.0

// ── Model: identity conv1x1 [1,16,1,8] ────────────────────────────────────
// Uses the exact MIL syntax generated by libane's MilBuilder (known to compile).
// Weight tensor: [OC=16, IC=16, kH=1, kW=1] = 256 fp16 values.
// With diagonal = 1.0, output equals input (identity mapping).

static const char* kMIL =
    "program(1.3)\n"
    "[buildInfo = dict<string, string>({"
    "    {\"coremlc-component-MIL\", \"3510.2.1\"},"
    "    {\"coremltools-version\", \"9.0\"}"
    "})]\n"
    "{\n"
    "    func main<ios18>(tensor<fp16, [1, 16, 1, 8]> x) {\n"
    "        string pt = const()[name=string(\"pt\"), val=string(\"valid\")];\n"
    "        tensor<int32, [2]> st = const()[name=string(\"st\"), val=tensor<int32, [2]>([1,1])];\n"
    "        tensor<int32, [4]> pd = const()[name=string(\"pd\"), val=tensor<int32, [4]>([0,0,0,0])];\n"
    "        tensor<int32, [2]> dl = const()[name=string(\"dl\"), val=tensor<int32, [2]>([1,1])];\n"
    "        int32 gr = const()[name=string(\"gr\"), val=int32(1)];\n"
    "        tensor<fp16, [16,16,1,1]> W = const()[name=string(\"W\"),\n"
    "            val=tensor<fp16, [16,16,1,1]>(\n"
    "                BLOBFILE(path=string(\"@model_path/weights/weight.bin\"),\n"
    "                         offset=uint64(64)))];\n"
    "        tensor<fp16, [1,16,1,8]> y = conv(\n"
    "            dilations=dl, groups=gr, pad=pd, pad_type=pt, strides=st,\n"
    "            weight=W, x=x)[name=string(\"y\")];\n"
    "    } -> (y);\n"
    "}\n";

// ── Weight blob builders ───────────────────────────────────────────────────

// Builds a 256-element [16×16] fp16 matrix with `diag_val` on the diagonal.
// Returns NSData with the 128-byte ANE blob header prepended.
//
// Header layout (matches Orion make_blobfile() and libane WeightBlob):
//   [0]      = 0x01   file type
//   [4]      = 0x02   file version
//   [64..67] = 0xDEADBEEF LE  chunk magic
//   [68]     = 0x01   chunk type
//   [72..75] = weight_bytes (uint32 LE)   byte count of fp16 data
//   [80..83] = 128    (uint32 LE)  byte offset from blob start where fp16 data begins
//   [128..]  = raw fp16 weight data
static NSData* make_weight_blob(uint16_t diag_val) {
    uint16_t w[16 * 16] = {};
    for (int i = 0; i < 16; ++i) w[i * 16 + i] = diag_val;

    size_t weight_bytes = sizeof(w);
    size_t blob_len = 128 + weight_bytes;
    uint8_t* blob = (uint8_t*)calloc(1, blob_len);

    // File header [0..63]
    blob[0] = 0x01; blob[4] = 0x02;

    // Chunk header [64..127]
    uint32_t magic = 0xDEADBEEF;
    memcpy(blob + 64, &magic, 4);
    blob[68] = 0x01;
    uint32_t sz = (uint32_t)weight_bytes;
    memcpy(blob + 72, &sz, 4);
    uint32_t data_offset = 128;
    memcpy(blob + 80, &data_offset, 4);  // ← required: tells ANE where fp16 data starts

    // Weight data [128..]
    memcpy(blob + 128, w, weight_bytes);

    NSData* d = [NSData dataWithBytes:blob length:blob_len];
    free(blob);
    return d;
}

// ── IOSurface helpers ──────────────────────────────────────────────────────

static IOSurfaceRef make_ios(size_t bytes) {
    size_t aligned = ((bytes + 63) & ~63UL);
    if (aligned < 49152) aligned = 49152;
    NSDictionary* props = @{
        (id)kIOSurfaceWidth:           @(aligned),
        (id)kIOSurfaceHeight:          @1,
        (id)kIOSurfaceBytesPerElement: @1,
        (id)kIOSurfacePixelFormat:     @0,
    };
    return IOSurfaceCreate((CFDictionaryRef)props);
}

static void write_ios_fill(IOSurfaceRef ios, uint16_t val, int count) {
    IOSurfaceLock(ios, 0, nullptr);
    uint16_t* base = (uint16_t*)IOSurfaceGetBaseAddress(ios);
    for (int i = 0; i < count; ++i) base[i] = val;
    IOSurfaceUnlock(ios, 0, nullptr);
}

// Read first `count` fp16 values as floats
static void read_ios_fp16(IOSurfaceRef ios, float* out, int count) {
    IOSurfaceLock(ios, kIOSurfaceLockReadOnly, nullptr);
    const uint16_t* base = (const uint16_t*)IOSurfaceGetBaseAddress(ios);
    for (int i = 0; i < count; ++i) {
        uint16_t h = base[i];
        uint32_t s = (h & 0x8000) << 16;
        uint32_t e = (h >> 10) & 0x1F;
        uint32_t m = h & 0x3FF;
        uint32_t fb;
        if (e == 0)       fb = s | (m << 13);
        else if (e == 31) fb = s | 0x7F800000 | (m << 13);
        else              fb = s | ((e + 112) << 23) | (m << 13);
        memcpy(&out[i], &fb, 4);
    }
    IOSurfaceUnlock(ios, kIOSurfaceLockReadOnly, nullptr);
}

// ── Compile + load at a given model_dir with specific weight data ──────────

static id compile_and_load_at(Class cls_Desc, Class cls_Model,
                               NSData* mil_data, NSData* wdata,
                               NSString* model_dir) {
    NSString* wkey = @"@model_path/weights/weight.bin";
    NSDictionary* weights_dict = @{ wkey: @{@"offset": @0, @"data": wdata} };

    SEL sel_desc = sel_registerName("modelWithMILText:weights:optionsPlist:");
    typedef id (*DescFn)(Class, SEL, NSData*, NSDictionary*, id);
    id descriptor = ((DescFn)objc_msgSend)(cls_Desc, sel_desc, mil_data, weights_dict, nil);
    if (!descriptor) { fprintf(stderr, "[-] Descriptor failed\n"); return nil; }

    SEL sel_mm = sel_registerName("inMemoryModelWithDescriptor:");
    typedef id (*ModelFn)(Class, SEL, id);
    id model = ((ModelFn)objc_msgSend)(cls_Model, sel_mm, descriptor);
    if (!model) { fprintf(stderr, "[-] Model failed\n"); return nil; }

    SEL sel_hexID = sel_registerName("hexStringIdentifier");
    NSString* hex_id = ((NSString*(*)(id,SEL))objc_msgSend)(model, sel_hexID);

    // Use caller-provided model_dir if set; otherwise derive from hex ID.
    NSString* mdir = model_dir ? model_dir
                               : [NSTemporaryDirectory() stringByAppendingPathComponent:hex_id];
    NSString* wdir = [mdir stringByAppendingPathComponent:@"weights"];
    NSFileManager* fm = [NSFileManager defaultManager];
    [fm createDirectoryAtPath:wdir withIntermediateDirectories:YES attributes:nil error:nil];
    [mil_data writeToFile:[mdir stringByAppendingPathComponent:@"model.mil"] atomically:YES];
    [wdata writeToFile:[wdir stringByAppendingPathComponent:@"weight.bin"] atomically:YES];

    NSError* err = nil;
    typedef BOOL (*QoSFn)(id, SEL, unsigned int, id, NSError**);
    if (!((QoSFn)objc_msgSend)(model, sel_registerName("compileWithQoS:options:error:"),
                                kQoS, @{}, &err) || err) {
        fprintf(stderr, "[-] Compile failed: %s\n",
                err ? [[err localizedDescription] UTF8String] : "unknown");
        return nil;
    }
    err = nil;
    if (!((QoSFn)objc_msgSend)(model, sel_registerName("loadWithQoS:options:error:"),
                                kQoS, @{}, &err) || err) {
        fprintf(stderr, "[-] Load failed: %s\n",
                err ? [[err localizedDescription] UTF8String] : "unknown");
        return nil;
    }
    return model;
}

// ── Execute with all-1.0 input, return first 8 output values ──────────────

static bool do_execute(id model, Class cls_IOS, Class cls_Req,
                       IOSurfaceRef in_ios, IOSurfaceRef out_ios,
                       float* out_vals, int count) {
    SEL sel_iosobj = sel_registerName("objectWithIOSurface:");
    typedef id (*SurfFn)(Class, SEL, IOSurfaceRef);
    id in_obj  = ((SurfFn)objc_msgSend)(cls_IOS, sel_iosobj, in_ios);
    id out_obj = ((SurfFn)objc_msgSend)(cls_IOS, sel_iosobj, out_ios);

    SEL sel_req = sel_registerName(
        "requestWithInputs:inputIndices:outputs:outputIndices:"
        "weightsBuffer:perfStats:procedureIndex:");
    typedef id (*ReqFn)(Class, SEL,
                        NSArray*, NSArray*, NSArray*, NSArray*,
                        id, id, NSUInteger);
    id request = ((ReqFn)objc_msgSend)(
        cls_Req, sel_req,
        @[in_obj], @[@0], @[out_obj], @[@0], nil, nil, (NSUInteger)0);
    if (!request) { fprintf(stderr, "[-] Request failed\n"); return false; }

    NSError* err = nil;
    typedef BOOL (*EvalFn)(id, SEL, unsigned int, id, id, NSError**);
    BOOL ok = ((EvalFn)objc_msgSend)(model,
                                     sel_registerName("evaluateWithQoS:options:request:error:"),
                                     kQoS, @{}, request, &err);
    if (!ok || err) {
        fprintf(stderr, "[-] Eval failed: %s\n",
                err ? [[err localizedDescription] UTF8String] : "unknown");
        return false;
    }
    read_ios_fp16(out_ios, out_vals, count);
    return true;
}

// ── Main ───────────────────────────────────────────────────────────────────

int main(void) {
    @autoreleasepool {
        void* fh = dlopen(kFrameworkPath, RTLD_NOW | RTLD_LOCAL);
        if (!fh) { fprintf(stderr, "dlopen failed: %s\n", dlerror()); return 1; }

        Class cls_Desc  = NSClassFromString(@"_ANEInMemoryModelDescriptor");
        Class cls_Model = NSClassFromString(@"_ANEInMemoryModel");
        Class cls_IOS   = NSClassFromString(@"_ANEIOSurfaceObject");
        Class cls_Req   = NSClassFromString(@"_ANERequest");
        if (!cls_Desc || !cls_Model || !cls_IOS || !cls_Req) {
            fprintf(stderr, "[-] Required classes not found\n"); return 1;
        }

        NSData* mil_data = [NSData dataWithBytes:kMIL length:strlen(kMIL)];
        NSData* wdata_1x = make_weight_blob(kFP16_1);  // diagonal = 1.0
        NSData* wdata_2x = make_weight_blob(kFP16_2);  // diagonal = 2.0

        // ── Phase 1: Compile with diagonal = 1.0 ──────────────────────────
        printf("=== probe_delta_reload ===\n\n");
        printf("[1] Compiling identity conv1x1 [1,16,1,8] with diagonal weight = 1.0...\n");

        id model = compile_and_load_at(cls_Desc, cls_Model, mil_data, wdata_1x, nil);
        if (!model) { printf("\nDone.\n"); return 1; }

        // Capture model_dir from the hex ID so we can overwrite the weight file
        SEL sel_hexID = sel_registerName("hexStringIdentifier");
        NSString* hex_id = ((NSString*(*)(id,SEL))objc_msgSend)(model, sel_hexID);
        NSString* model_dir = [NSTemporaryDirectory() stringByAppendingPathComponent:hex_id];
        printf("[+] Compiled and loaded. model_dir = %s\n", [model_dir UTF8String]);

        IOSurfaceRef in_ios  = make_ios(16 * 8 * 2);
        IOSurfaceRef out_ios = make_ios(16 * 8 * 2);

        // Input: all 1.0
        write_ios_fill(in_ios, kFP16_1, 16 * 8);

        printf("\n[2] Executing with input = all 1.0 fp16...\n");
        static constexpr int kReadN = 8;  // read first 8 output values
        float out1[kReadN] = {};
        write_ios_fill(out_ios, kFP16_0, kReadN);  // zero the output surface

        if (!do_execute(model, cls_IOS, cls_Req, in_ios, out_ios, out1, kReadN)) {
            printf("\nDone.\n"); return 1;
        }
        printf("    output[0..%d] = [", kReadN - 1);
        for (int i = 0; i < kReadN; ++i) printf("%.3f%s", out1[i], i < kReadN-1 ? ", " : "");
        printf("]\n");
        printf("    (diagonal=1.0 phase: recorded as baseline)\n");

        // ── Phase 2: Delta reload with diagonal = 2.0 ─────────────────────
        printf("\n[3] Delta reload: overwriting weight file with diagonal = 2.0...\n");

        // Unload
        NSError* err = nil;
        typedef BOOL (*UnloadFn)(id, SEL, unsigned int, NSError**);
        ((UnloadFn)objc_msgSend)(model, sel_registerName("unloadWithQoS:error:"), kQoS, &err);
        printf("    unloadWithQoS: done%s\n", err ? " (with error)" : "");

        // Overwrite weight file on disk
        NSString* wpath = [[model_dir stringByAppendingPathComponent:@"weights"]
                                      stringByAppendingPathComponent:@"weight.bin"];
        [wdata_2x writeToFile:wpath atomically:YES];
        printf("    wrote diagonal=2.0 weight to %s\n", [wpath UTF8String]);

        // Reload (no compile)
        err = nil;
        typedef BOOL (*QoSFn)(id, SEL, unsigned int, id, NSError**);
        BOOL loaded = ((QoSFn)objc_msgSend)(model,
                                             sel_registerName("loadWithQoS:options:error:"),
                                             kQoS, @{}, &err);
        printf("    loadWithQoS: %s%s\n", loaded ? "OK" : "FAILED",
               err ? [[NSString stringWithFormat:@" (%@)", [err localizedDescription]] UTF8String] : "");
        if (!loaded) { printf("\nDone.\n"); return 1; }

        // ── Phase 3: Execute again ─────────────────────────────────────────
        printf("\n[4] Executing after delta reload (input still all 1.0)...\n");
        float out2[kReadN] = {};
        write_ios_fill(out_ios, kFP16_0, kReadN);  // zero output surface to avoid stale reads

        if (!do_execute(model, cls_IOS, cls_Req, in_ios, out_ios, out2, kReadN)) {
            printf("\nDone.\n"); return 1;
        }
        printf("    output[0..%d] = [", kReadN - 1);
        for (int i = 0; i < kReadN; ++i) printf("%.3f%s", out2[i], i < kReadN-1 ? ", " : "");
        printf("]\n");

        // ── Verdict ────────────────────────────────────────────────────────
        // Check how many output values changed between phase 1 and phase 2.
        int changed = 0;
        float max_delta = 0;
        for (int i = 0; i < kReadN; ++i) {
            float d = fabsf(out2[i] - out1[i]);
            if (d > 0.05f) changed++;
            if (d > max_delta) max_delta = d;
        }

        printf("\n=== VERDICT ===\n");
        printf("  Values changed: %d / %d  (max delta = %.4f)\n", changed, kReadN, max_delta);
        if (changed > 0) {
            printf("  [+] WEIGHTS UPDATED — output changed after delta reload.\n");
            printf("      delta reload correctly re-reads weights from disk on this firmware.\n");
            printf("      libane_delta_reload() is valid for weight updates.\n");
        } else {
            printf("  [-] WEIGHTS NOT UPDATED — output identical before and after reload.\n");
            printf("      ANE baked the diagonal=1.0 weights at compile time.\n");
            printf("      Overwriting the disk file had no effect on execution.\n");
            printf("      --> libane_delta_reload() should NOT be used for weight updates.\n");
            printf("      --> The 8.5x speed benefit (no recompile) may still hold,\n");
            printf("          but the executed weights are from the original compile.\n");
        }

        CFRelease(in_ios);
        CFRelease(out_ios);
        printf("\nDone.\n");
        return 0;
    }
}
